<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <center> <h1>AIR QUALITY</h1></center><br><br>
<table class="table table-striped">
  <thead>
    <tr>
     
      <th scope="col"><b>FIELD</b></th>
      <th scope="col"><b>CONDITIONS</b></th>
    </tr>
  </thead>
  <tbody>
    <tr>
     
      <td>OZONE</td>
      <td> <?php echo $weather['current']['air_quality']['o3']; ?></td>
    </tr>
    <tr>
    
      <td>CARBON-DI-OXIDE</td>
      <td> <?php echo $weather['current']['air_quality']['co']; ?></td>
    </tr>
    <tr>
   
      <td>NITROGEN-DI-OXIDE</td>
      <td> <?php echo $weather['current']['air_quality'] ['no2']; ?></td>
    </tr>
    <tr>
   
   <td>SULPHUR-DI-OXIDE</td>
   <td> <?php echo $weather['current']['air_quality']['so2']; ?></td>
 </tr>
 <tr>
   
   <td>PM2_5</td>
   <td> <?php echo $weather['current']['air_quality']['pm2_5']; ?></td>
 </tr>
 <tr>
   
   <td>PM10</td>
   <td> <?php echo $weather['current']['air_quality'] ['pm10']; ?></td>
 </tr>
 <tr>
   
   <td>INFRA INDEX</td>
   <td> <?php echo $weather['current']['air_quality']['gb-defra-index']; ?></td>
 </tr>
  </tbody>
</table>
</body>
</html>

